### PR TITLE
Euicc: Add support for OnePlus ACE3 OP5CF9L1

### PR DESCRIPTION
**Pull request by LucasBlackLu**
* Fix following errors

E AndroidRuntime: java.lang.RuntimeException: Cannot find SIM slot mapping for device: OP5CF9L1
E AndroidRuntime: Caused by: java.lang.RuntimeException: Cannot find SIM slot mapping for device: OP5CF9L1

### CODE REVIEW

**Comment by inferno0230** [comment]
When did the OnePlus Ace 3 start supporting eSIM?

**Comment by LucasBlackLu** [comment]
it's not esim, it would keep sim card manager fc in derp-15

**Comment by LucasBlackLu** [comment]
BTW, i have 2 sim card and ace3 support dual sim card

**Comment by inferno0230** [comment]
> it's not esim, it would keep sim card manager fc in derp-15

https://t.me/OnePlus12RGlobalChat/112059

**Comment by LucasBlackLu** [comment]
Done, It's my own rom source fault, I built pixel before and forgot to make clean, it bring sim card manager fc to aston

**Comment by LucasBlackLu** [comment]
OnePlus ACE3 doesn't support seim

**Pull request closed without merging**
